name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./apps/web
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_PERSONAL_ACCOUNT_TOKEN }}
      - name: Build Project Artifacts
        run: pnpm web:build
      # - name: Build Project Artifacts
      #   working-directory: ./apps/web
      #   run: vercel build --token=${{ secrets.VERCEL_PERSONAL_ACCOUNT_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   working-directory: ./apps/web
      #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_PERSONAL_ACCOUNT_TOKEN }}
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_PERSONAL_ACCOUNT_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          # vercel-args: '--prod' #Optional
          vercel-org-id: ${{ env.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }} #Required
          working-directory: ./apps/web
